//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyrotechnics.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deck
    {
        public int GameId { get; set; }
        public int Order { get; set; }
        public int CardId { get; set; }
        public int CardStateId { get; set; }
        public int ColorId { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual CardState CardState { get; set; }
        public virtual Color Color { get; set; }
        public virtual Game Game { get; set; }
    }
}
